Fork Update
laptopwiki/laptopwiki.github.io pull request #40
Opened 2022-08-17 17:44 UTC by kirakenchin

Ignore Vantage Reinstall Guide

2022-08-21 00:36 UTC, nonkerdoob commented
Resolve Comments

2022-08-21 00:38 UTC, nonkerdoob requested changes
Undervolt username on GitHub is Undervoltologist

2022-08-21 17:14 UTC, kirakenchin commented on _drafts/max-fans.md
> +grand_parent: General
yeah it should be under legion laptops. i am not sure if RWE works in every laptop

2022-08-25 09:38 UTC, nonkerdoob requested changes

2022-08-27 01:14 UTC, nonkerdoob approved these changes

2022-08-27 01:14 UTC, merged