Update no-os-legion.md
laptopwiki/laptopwiki.github.io pull request #44
Opened 2022-09-09 13:23 UTC by averyspeedybird

Fixed a few typos and grammatical issues, made it slightly more clear

2022-09-09 14:19 UTC, nonkerdoob requested changes

2022-09-09 14:19 UTC, nonkerdoob commented on _guides/legion/getting-started/no-os-legion.md
> +discord: ['ClemFab#0741', 'mind12#3390', 'nibi030#0077', 'Kazmir#7360', 'Kaobalt#0001', 'Speedbird001#4677']
Add your GitHub username to contributors in the format ``['username']``> No need for discord tag. 

They are for people without GitHub accounts.

2022-10-06 23:42 UTC, kirakenchin commented on _guides/legion/getting-started/no-os-legion.md
> +- If your laptop is brand new, you can choose to go through [this checklist](https://new.laptopwiki.eu/guides/general/getting-started/laptop-new/) to check it for issues
you mean (https://guides/general/getting-started/laptop-new/)? or (guides/general/getting-started/laptop-new/)?

2022-10-07 01:24 UTC, nonkerdoob commented on _guides/legion/getting-started/no-os-legion.md
> +- If your laptop is brand new, you can choose to go through [this checklist](https://new.laptopwiki.eu/guides/general/getting-started/laptop-new/) to check it for issues
```/guides/general/getting-started/laptop-new/```

2022-10-16 09:31 UTC, nonkerdoob approved these changes

2022-10-16 09:31 UTC, merged